language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - make all

env:
  matrix:
    - RUST_BACKTRACE=1
    - RELEASE=true

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
